//
// CandidateJob.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateJob: JSONEncodable {

    public var actions: Actions?
    public var id: String?
    public var startsOn: NSDate?
    public var title: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["startsOn"] = self.startsOn?.encodeToJSON()
        nillableDictionary["title"] = self.title
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
