//
// CandidateWebDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateWebDetails: JSONEncodable {

    public var facebook: String?
    public var linkedin: String?
    public var skype: String?
    public var twitter: String?
    public var website: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["facebook"] = self.facebook
        nillableDictionary["linkedin"] = self.linkedin
        nillableDictionary["skype"] = self.skype
        nillableDictionary["twitter"] = self.twitter
        nillableDictionary["website"] = self.website
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
