//
// CandidateLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateLocation: JSONEncodable {

    public var address: String?
    public var city: String?
    public var country: String?
    public var countryCode: String?
    public var postalCode: String?
    public var region: String?
    public var regionCode: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["address"] = self.address
        nillableDictionary["city"] = self.city
        nillableDictionary["country"] = self.country
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["postalCode"] = self.postalCode
        nillableDictionary["region"] = self.region
        nillableDictionary["regionCode"] = self.regionCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
