//
// Candidate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Candidate: JSONEncodable {

    public var education: [CandidateEducation]?
    public var email: String?
    public var experience: [CandidateExperience]?
    public var firstName: String?
    public var lastName: String?
    public var location: CandidateLocation?
    public var phoneNumber: String?
    public var sourceDetails: CandidateSource?
    public var tags: [String]?
    public var web: CandidateWebDetails?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["education"] = self.education?.encodeToJSON()
        nillableDictionary["email"] = self.email
        nillableDictionary["experience"] = self.experience?.encodeToJSON()
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["phoneNumber"] = self.phoneNumber
        nillableDictionary["sourceDetails"] = self.sourceDetails?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["web"] = self.web?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
