//
// CandidateStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateStatus: JSONEncodable {

    public enum Status: String { 
        case Lead = "LEAD"
        case New = "NEW"
        case InReview = "IN_REVIEW"
        case Interview = "INTERVIEW"
        case Offered = "OFFERED"
        case Hired = "HIRED"
        case Rejected = "REJECTED"
        case Withdrawn = "WITHDRAWN"
        case Transferred = "TRANSFERRED"
    }
    
    public var startsOn: NSDate?
    public var status: Status?
    public var subStatus: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["startsOn"] = self.startsOn?.encodeToJSON()
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["subStatus"] = self.subStatus
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
