//
// CandidateListElem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateListElem: JSONEncodable {

    public var actions: Actions?
    public var averageRating: Double?
    public var createdOn: NSDate?
    public var email: String?
    public var firstName: String?
    public var id: String?
    public var Swaggerinternal: Bool?
    public var lastName: String?
    public var location: CandidateLocation?
    public var primaryAssignment: CandidateAssignment?
    public var secondaryAssignments: [CandidateAssignment]?
    public var tags: [String]?
    public var updatedOn: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["averageRating"] = self.averageRating
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        nillableDictionary["email"] = self.email
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["id"] = self.id
        nillableDictionary["Swaggerinternal"] = self.Swaggerinternal
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["primaryAssignment"] = self.primaryAssignment?.encodeToJSON()
        nillableDictionary["secondaryAssignments"] = self.secondaryAssignments?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["updatedOn"] = self.updatedOn?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
