//
// CandidateEducation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateEducation: JSONEncodable {

    public var current: Bool?
    public var degree: String?
    public var description: String?
    public var endDate: String?
    public var institution: String?
    public var location: String?
    public var major: String?
    public var startDate: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["current"] = self.current
        nillableDictionary["degree"] = self.degree
        nillableDictionary["description"] = self.description
        nillableDictionary["endDate"] = self.endDate
        nillableDictionary["institution"] = self.institution
        nillableDictionary["location"] = self.location
        nillableDictionary["major"] = self.major
        nillableDictionary["startDate"] = self.startDate
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
