//
// CandidateProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CandidateProperty: JSONEncodable {

    public enum SwaggerType: String { 
        case Boolean = "BOOLEAN"
        case Country = "COUNTRY"
        case Currency = "CURRENCY"
        case Date = "DATE"
        case Number = "NUMBER"
        case Percent = "PERCENT"
        case Region = "REGION"
        case Text = "TEXT"
        case User = "USER"
        case SingleSelect = "SINGLE_SELECT"
    }
    
    public var actions: Actions?
    public var id: String?
    public var label: String?
    public var type: SwaggerType?
    public var value: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["label"] = self.label
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["value"] = self.value
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
