//
// Compensation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Compensation: JSONEncodable {

    public var currency: String?
    public var max: Int?
    public var min: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["currency"] = self.currency
        nillableDictionary["max"] = self.max
        nillableDictionary["min"] = self.min
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
