//
// HiringTeamMember.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class HiringTeamMember: JSONEncodable {

    public enum Role: String { 
        case HiringManager = "HIRING_MANAGER"
        case InterviewTeam = "INTERVIEW_TEAM"
        case Recruiter = "RECRUITER"
        case Executive = "EXECUTIVE"
        case Coordinator = "COORDINATOR"
    }
    
    public var actions: Actions?
    public var id: String?
    public var role: Role?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["role"] = self.role?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
