//
// JobAdSections.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JobAdSections: JSONEncodable {

    public var additionalInformation: JobAdSection?
    public var companyDescription: JobAdSection?
    public var jobDescription: JobAdSection?
    public var qualifications: JobAdSection?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["additionalInformation"] = self.additionalInformation?.encodeToJSON()
        nillableDictionary["companyDescription"] = self.companyDescription?.encodeToJSON()
        nillableDictionary["jobDescription"] = self.jobDescription?.encodeToJSON()
        nillableDictionary["qualifications"] = self.qualifications?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
