//
// JobList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JobList: JSONEncodable {

    public var content: [JobListElem]?
    public var limit: Int?
    public var offset: Int?
    public var totalFound: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["content"] = self.content?.encodeToJSON()
        nillableDictionary["limit"] = self.limit
        nillableDictionary["offset"] = self.offset
        nillableDictionary["totalFound"] = self.totalFound
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
