//
// JobListElem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JobListElem: JSONEncodable {

    public enum Status: String { 
        case Created = "CREATED"
        case Sourcing = "SOURCING"
        case Filled = "FILLED"
        case Cancelled = "CANCELLED"
        case Interview = "INTERVIEW"
        case Offer = "OFFER"
        case Other = "OTHER"
    }
    
    public var actions: Actions?
    public var createdOn: NSDate?
    public var id: String?
    public var location: Location?
    public var refNumber: String?
    public var status: Status?
    public var title: String?
    public var updatedOn: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["refNumber"] = self.refNumber
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["title"] = self.title
        nillableDictionary["updatedOn"] = self.updatedOn?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
