//
// JobStatusHistoryListElem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JobStatusHistoryListElem: JSONEncodable {

    public enum Status: String { 
        case Created = "CREATED"
        case Sourcing = "SOURCING"
        case Filled = "FILLED"
        case Cancelled = "CANCELLED"
        case Interview = "INTERVIEW"
        case Offer = "OFFER"
        case Other = "OTHER"
    }
    
    public var actions: Actions?
    public var changedOn: NSDate?
    public var status: Status?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["changedOn"] = self.changedOn?.encodeToJSON()
        nillableDictionary["status"] = self.status?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
