//
// Offer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Offer: JSONEncodable {

    public var actions: Actions?
    public var createdOn: NSDate?
    public var id: String?
    public var properties: OfferProperties?
    public var status: String?
    public var updatedOn: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["properties"] = self.properties?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["updatedOn"] = self.updatedOn?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
